### ISSUE TITLE
Github Permissions

### ISSUE THREAD

**Issue by workergnome** [annonatate/annonatate#2]
Hey!  

Would love to play with this—really nice work.  Wonder if it's possible to review the permissions it's asking for on Github?  They're pretty extensive, and I'm not really supposed to give full permissions for all of Getty's repos to third party apps like this.

Thanks!

**Comment by workergnome** [comment]
FYI, this is the permission list I'm asked to grant.

![Screen Shot 2021-03-11 at 9 32 09 AM](https://user-images.githubusercontent.com/34536/110829188-b0301a80-824c-11eb-93c4-e77772ff2ae0.png)

**Comment by dnoneill** [comment]
@workergnome I am happy to talk to you about this but it does need to be able to access repositories in order to write to them and to actually find the repositories for the application. If you can think of a way around this that would be great but right now there isn't much I can do. Sorry it has taken me so long to get to this I just saw this and now I need to go check my alert settings.

**Comment by workergnome** [comment]
Of course!  It definitely needs access to repos, but it might not need to, say, update my personal email address.

**Comment by dnoneill** [comment]
Yeah I have that in there so you can update your display name because that is what is used for the creator information. I think if you can change the url to log into to the scopes you want. I will look into it.

**Comment by workergnome** [comment]
Thanks!  Appreciate you taking the time.

**Comment by dnoneill** [comment]
@workergnome I have looked into this. I am removing the access to all user data. The only thing I was using it for was the ability to update the display name on GitHub and that does not seem worth requiring access to this. I am replacing the ability to update in the app with a link to the profile https://github.com/settings/profile. This should be available in the next release. I will let you know when that is.

**Comment by workergnome** [comment]
Oh, great!  Thank you!

**Comment by dnoneill** [comment]
@workergnome Deployed to production. If you have already logged in you will have to revoke permissions to log in with the new credentials. https://github.com/settings/applications
