### ISSUE TITLE
Add thumbnail images for navigation

### ISSUE THREAD

**Issue by D-Groenewegen** [annonatate/annonatate#3]
First of all, thanks a lot for your work! 

In the first tabbed section of https://annonatate.herokuapp.com, I pulled in manuscript images from the National Library of Wales using this manifest: https://damsssl.llgc.org.uk/iiif/2.0/4654784/manifest.json

Loading the images worked like a charm and links were provided to individual manuscript pages, but the thumbnail images for these links were missing, as you can see in this screenshot: 

<img width="1144" alt="Screenshot 2021-05-31 at 12 31 59" src="https://user-images.githubusercontent.com/10888726/120181679-b14e6380-c20d-11eb-9311-37e2121f105b.png">

It also occurred to me that in the case of navigation being used for browsing multiple images, it would be more user-friendly to keep it expanded. The situation right now is that every time you click to see a new manuscript pages, the navigation returns to its collapsed state.

**Comment by annonatate** [comment]
@D-Groenewegen This is now fixed and live on annonatate. You might need to clear your cache to get it to work. I also took your advice. If the manifest have more than one image in the manifest the thumbnails will stay open, otherwise they will close.

**Comment by D-Groenewegen** [comment]
Many thanks, I got it to work without the need to clear the cache.
