### ISSUE TITLE
Error 500 on my account

### ISSUE THREAD

**Issue by liladude** [annonatate/annonatate#4]
Hi, sorry to bother. I have created my annonatate repo last year, now it seem to be out of date and I am unsure if this is the cause, but when I click "login" on the herokuapp page I often get internal error or error 500. Any hints on how to properly update my code?

Best regards
Elisa

**Comment by dnoneill** [comment]
@liladude There are two PR to fix your repository.

**Comment by liladude** [comment]
Ouch, my bad! some leftovers of very early testing! Thank you!
