### ISSUE TITLE
Rotating images

### ISSUE THREAD

**Issue by liladude** [annonatate/annonatate#5]
Sorry for this new request. I seem unable to find a way to rotate my images in the storyboard. I have images in a book that needs to be rotated 90° clockwise, any idea if I should edit the parameter in the manifest or in the annotation manually?
Thank you again.
Elisa

**Comment by dnoneill** [comment]
I would suggest rotating the image so that it always shows up the correct way. You can rotate the image in the storyboards with the `r` keyboard shortcut. Right now there is a bug if you use this method but I am in the process of fixing it.

**Comment by liladude** [comment]
Thank you! I will try to create special manifest with the rotated images and annotate those images. I have digged though the informations on IIIF manuals and only the image api let you rotate, so I guess it can be set on annotation level!
Thank you again for the tip on R rotation!
